apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease

metadata:
  name: demo-app
  namespace: default

spec:
  interval: 1m

  chart:
    spec:
      chart: ./demo-app
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system

  values:
    replicaCount: 1

    image:
      repository: demo
      tag: v1
      pullPolicy: IfNotPresent

    service:
      type: NodePort
